# Generated by Django 6.0.2 on 2026-03-04 09:30

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("academics", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AttendanceRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "attendance_date",
                    models.DateField(default=django.utils.timezone.localdate),
                ),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "status",
                    models.CharField(
                        choices=[("Present", "Present"), ("Absent", "Absent")],
                        default="Present",
                        max_length=10,
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="academics.course",
                    ),
                ),
                (
                    "lecturer",
                    models.ForeignKey(
                        limit_choices_to={"role": "lecturer"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="lecturer_attendance",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        limit_choices_to={"role": "student"},
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="academics.subject",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["student"], name="attendance__student_bf8a5d_idx"
                    ),
                    models.Index(
                        fields=["attendance_date"],
                        name="attendance__attenda_ee6011_idx",
                    ),
                    models.Index(
                        fields=["subject"], name="attendance__subject_fa8f74_idx"
                    ),
                ],
                "unique_together": {("student", "subject", "attendance_date")},
            },
        ),
    ]
