# Generated by Django 6.0.2 on 2026-02-24 13:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AttendanceRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("admission_id", models.CharField(db_index=True, max_length=50)),
                ("course_code", models.CharField(max_length=10)),
                ("year", models.IntegerField()),
                ("subject_name", models.CharField(max_length=100)),
                ("lecturer_id", models.CharField(max_length=50)),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                ("status", models.CharField(default="Present", max_length=10)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["admission_id"], name="attendance__admissi_8529bb_idx"
                    ),
                    models.Index(
                        fields=["course_code", "year"],
                        name="attendance__course__6e61f2_idx",
                    ),
                    models.Index(
                        fields=["timestamp"], name="attendance__timesta_01c0dc_idx"
                    ),
                ],
            },
        ),
    ]
