# Generated by Django 6.0.2 on 2026-02-24 13:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0001_initial"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="attendancerecord",
            name="attendance__course__6e61f2_idx",
        ),
        migrations.RemoveIndex(
            model_name="attendancerecord",
            name="attendance__timesta_01c0dc_idx",
        ),
        migrations.AddField(
            model_name="attendancerecord",
            name="attendance_date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterUniqueTogether(
            name="attendancerecord",
            unique_together={("admission_id", "subject_name", "attendance_date")},
        ),
        migrations.AddIndex(
            model_name="attendancerecord",
            index=models.Index(
                fields=["attendance_date"], name="attendance__attenda_ee6011_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="attendancerecord",
            index=models.Index(
                fields=["subject_name"], name="attendance__subject_549142_idx"
            ),
        ),
    ]
