# Generated by Django 6.0.2 on 2026-03-05 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0003_complaint"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Complaint",
        ),
    ]
