# Generated by Django 6.0.2 on 2026-03-05 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0004_delete_complaint"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendancerecord",
            name="allow_reenroll",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="attendancerecord",
            name="face_enrolled",
            field=models.BooleanField(default=False),
        ),
    ]
