# Generated by Django 6.0.2 on 2026-03-07 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0005_attendancerecord_allow_reenroll_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendancesession",
            name="restart_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="attendancesession",
            name="timer_minutes",
            field=models.IntegerField(default=5),
        ),
    ]
