# Generated by Django 6.0.2 on 2026-03-04 22:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0001_initial"),
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="course",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="academics.course",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="year",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
