# Generated by Django 6.0.2 on 2026-03-07 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_complaint"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="allow_reenroll",
            field=models.BooleanField(default=False),
        ),
    ]
